### ISSUE TITLE
node-fetch is not well-behaved on requests to `safaridriver`

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#277]
The fetch code in `@bigtest/webdriver` uses an abort controller to make sure that the request is always stopped even if it is in flight.

However, when using `bigtest server --launch safari`, it throws the following exception.

```
AbortError: The user aborted a request.
    at abort (@bigtest/example/todomvc/node_modules/node-fetch/lib/index.js:1412:16)
    at AbortSignal.abortAndFinalize (@bigtest/example/todomvc/node_modules/node-fetch/lib/index.js:1427:4)
    at AbortSignal.dispatchEvent (@bigtest/example/todomvc/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
    at abortSignal (@bigtest/example/todomvc/node_modules/abort-controller/dist/abort-controller.js:52:12)
    at AbortController.abort (@bigtest/example/todomvc/node_modules/abort-controller/dist/abort-controller.js:91:9)
    at Object.fetch (@bigtest/example/todomvc/node_modules/@bigtest/webdriver/dist/fetch.js:24:20)
    at fetch.next (<anonymous>)
    at @bigtest/example/todomvc/node_modules/effection/dist/effection.js:1:8019
    at n.r.advance (@bigtest/example/todomvc/node_modules/effection/dist/effection.js:1:7655)
    at n.r.trapExit (@bigtest/example/todomvc/node_modules/effection/dist/effection.js:1:7981) {
  type: 'aborted',
  message: 'The user aborted a request.'
```

The request is successful, and the browser _does_ launch. Finally, if the call to `controller.abort()` is removed, then it loads as expected. So something is up with `node-fetch` probably a bug or a race condition. We should either fix this in the underlying library upstream, or workaround it in our `fetch` implementation.

But why `safaridriver` in particular?

**Comment by cowboyd** [comment]
It turns out that safari driver was returning the headers first before the response thus triggering the request to be cancelled while it was still in-flight. This was resolved with thefrontside/effection#156 and so now safaridriver totally works!
