### ISSUE TITLE
Don't watch test files in CI mode

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#445]
We only need to build the bundle once for the test run, and so we don't need to consume all of the operating system resources needed to watching hundreds and hundreds of files. In fact, the default GitHub actions container whines about watches.

It's also sufficient to just issue one warning if possible.

```
node:3439) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/home/runner/work/trade/trade/simulation/src/index.ts'
35
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
36
    at Object.watch (fs.js:1445:34)
37
    at createFsWatchInstance (/home/runner/work/trade/trade/web/admin/node_modules/rollup/dist/shared/index.js:4400:15)
38
    at setFsWatchListener (/home/runner/work/trade/trade/web/admin/node_modules/rollup/dist/shared/index.js:4447:15)
39
    at NodeFsHandler._watchWithNodeFs (/home/runner/work/trade/trade/web/admin/node_modules/rollup/dist/shared/index.js:4602:14)
40
    at NodeFsHandler._handleFile (/home/runner/work/trade/trade/web/admin/node_modules/rollup/dist/shared/index.js:4666:23)
41
    at NodeFsHandler._addToNodeFs (/home/runner/work/trade/trade/web/admin/node_modules/rollup/dist/shared/index.js:4899:21)
42
    at async /home/runner/work/trade/trade/web/admin/node_modules/rollup/dist/shared/index.js:5875:21
43
    at async Promise.all (index 0)
```

**Comment by jnicklas** [comment]
Just realized that while we do switch off the file watching for the bundler as of #561, we still use chokidar in the manifest *generator* to watch the glob of test files and see if it changes.
