### ISSUE TITLE
Brainstorm ways to communicate expectation failures in interactors for those not familiar with the tabular format

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/bigtest#682]
In the course of developing the marketing material for interactors in the website, there was some confusion about how to interpret the error messages raised. Because error messaging is one of the crown jewels of BigTest, we want to make absolutely sure we make the impedance to understanding as low as possible. 

This issue is a placeholder to surface the cause of those issues and also to develop improvements.

**Comment by jbolda** [comment]
Getting into Interactors,  the table appears to be helpful, and I think I know what it is trying to accomplish. The problem that I'm running into is that I feel like I'm missing some context. The first column in your typical table is traditionally more of a label to help you distinguish between different rows. Also the selector is sometimes shown and sometimes isn't (depending on if it is being used), and wasn't immediately obvious that all of these columns are only shown if they're used (maybe due to the defaults being shown? I didn't know they were defaults until digging in more).

It seems like it might be helpful if we have a the first column describe what the element is, and always show the selector and a note if it is being used or not. It might also be helpful to note which filters are default, as sometimes we show filters if they're used, but we're always showing the defaults which isn't always obvious. Especially as we compose multiple interactors together, I think it will be more difficult to recall which items are default in which aren't, and what the "low level" or otherwise built-in interactors contain. If you're using an off-the-shelf or already written interactor, I think this will help save you from typos or missing items in the filter. It gives you a list of items that are close and might be potential matches.

If you are just working on a new interactor though, I feel that it's missing the context of "why". It isn't always quite clear if the issue is with the selector, the locator, or the filters. It does give you potential matches, but those are only correct if your selector and locator are correct. Without that label column and no context for the interactor, then it doesn't quite guide you to what the next debugging steps might be. That seems like a pretty open-ended statement, but I think if we slowly expose or guide the user in the debugging of the issue, that could become extremely helpful. This may be the best way to address the usability of the table as well. List out the potential failures a user might see, and test that we have some way to guide them to take the proper next step in debugging.

**Comment by cowboyd** [comment]
I see what you mean, so that we aren't talking in the abstract, can we compile a list of confusing error messages and what is confusing about it? That will help us have a concrete focus as we propose changes to make it better.

**Comment by jbolda** [comment]
I should have written some down as I go. I can start dropping them here with notes as I run across them again.

**Comment by jgnieuwhof** [comment]
I just came across a bit of a confusing one. As @jbolda's informed me, one of the default filters is `{ visible: true }`. It's a sensible default, but stops making sense once the interactor is used with a `{ visible: false }` filter.


For example:
```javascript

const element = ButtonInteractor('press me');



```

**Comment by jgnieuwhof** [comment]
Sorry for the spam that was completely unintentional 🙈

**Comment by jgnieuwhof** [comment]
I just came across one, where the fix could either be better documentation or a change in behaviour.

As I understand it, filters are used in two ways:
- "search" filters; used to locate the element, passed when instantiating the interactor
- "assertion" filters; used to assert on an element's state, passed to `has` or `is`

The "search" filters contain defaults, such as `{ visible: true }`. This makes sense most of the time, but break down if one specifies an "assertion" filter that conflicts with one of the "search" filters. Example:

```javascript
const button = ButtonInteractor('click me');

it('is not visible', () => button.is({ visible: false }));
```

Given a button that is not visible, this assertion will never run; instead this will fail with the following `NoSuchElementError`:
```
      NoSuchElementError: did not find button "click me", did you mean one of:
      
      ┃ button         ┃ visible: true ┃
      ┣━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━┫
      ┃ ✓ "click me"   ┃ ⨯ false       ┃

```

It's confusing because, at first glance, I can see my element in the table with its expected `{ visible: false }` state, which is exactly what both me and my assertion expected.

It's not clear that the second column header is the corresponding default "search" filter value. It may help to have headers above these columns, indicating that the first column is the element type, and the second column is the filter default.

Aside from the lack of clarity, it raises the question of whether or not this is the desired behaviour. As a consumer I would expect the "assertion" filter to override the default "search" filter. If the values are conflicting I can't think of a situation where I would want the search to fail rather than the assertion.

**Comment by jbolda** [comment]
Getting this error today that is rather confusing.

```shell
        FilterNotMatchingError: text field which is not visible and which is not disabled does not match filters:

        ┃ value: "2008-12-07T00:00:00.000+0000" ┃ visible: true ┃ disabled: false ┃
        ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━┫
        ┃ ⨯ "2008-04-17T00:00:00.000Z"          ┃ ⨯ false       ┃ ✓ false         ┃
            at tests/index.js:305946:27
            at converge (tests/index.js:304957:20)
```

It appears to not be finding this element that I am searching for. Not the `visible: true` vs false. (Setting disabled just to make certain that the defaults are not messing with me.)
```js
const hiddenInput = Bigtest.TextField({ visible: false, disabled: false });
```

**Comment by cowboyd** [comment]
@jgnieuwhof 

>As I understand it, filters are used in two ways:
>
>"search" filters; used to locate the element, passed when instantiating the interactor
>"assertion" filters; used to assert on an element's state, passed to has or is

I think I see what you're saying here, but want to clarify that you can (and should) use the same filters for both asserting and searching.

**Comment by cowboyd** [comment]
@jgnieuwhof 
> Given a button that is not visible, this assertion will never run; instead this will fail with the following NoSuchElementError:

This seems like a bug to me. Basically, what we're saying is that if a filter has a default, there's no way you can assert on the inverse of that default?

In other words the following is nonsense and should always fail:

```ts
await Button({visible: true}).is({visible: false});
```

But this should be true if the button itself is visible even if the default filter does not match

```ts
await Button().is({ visible: true });
```

**Comment by jgnieuwhof** [comment]
@cowboyd 

> I think I see what you're saying here, but want to clarify that you can (and should) use the same filters for both asserting and searching.

Thanks for asking for clarification; now having more experience with interactors I would have worded my comment differently 😅.

The "search" and "assertion" filters _are_ the same; their use differs. 
- `Button({ visible: true })` locates the element
- `Button().is({ visible: true })` asserts on the element

> This seems like a bug to me. Basically, what we're saying is that if a filter has a default, there's no way you can assert on the inverse of that default?

Yeah that was my experience.

As I would define it now; if a filter is used to locate the element, there's no way to assert on the inverse of the value used to locate the element.

If it sounds like a bug I'd be happy to write a failing test case to verify / illustrate.

**Comment by cowboyd** [comment]
So wait which case was it? `await Button({visible: true}).is({visible: false})` because one set of filters is applied before the other, so we only search for invisible elements amongst the visible ones.

On the other hand, `await Button().is({ visible: false })`  _should_ work.

**Comment by jgnieuwhof** [comment]
Ah, sorry, I misread your earlier comment.

>In other words the following is nonsense and should always fail:
>
> await Button({visible: true}).is({visible: false});

Understood, this fails as it should.

> On the other hand, `await Button().is({ visible: false })` should work.

Right, and currently it fails if the default is `{ visible: true }`).

**Comment by cowboyd** [comment]
Ah, in that case that  _definitely_ feels like a bug.

**Comment by cowboyd** [comment]
Ok, I've had a think about this and what about this as a way to start down the path to improvement. I think there are a few issues I've identified:

1. The explanatory text for an interactor is confusing.
1. Showing the actual value when it is the same as the expected is redundant (more on this later)
2. We show filters that might not be relevant. In other words, if someone used a filter to lookup an interactor, they probably don't want to see those filters spelled out in the failure message. They're going to be more interested about which assertion value didn't work 

As, @jgnieuwhof pointed out, we use filters not only to _identify_ elements, but also to make assertions about them. And our error messaging can be slightly different to accomodate these two use cases.

I propose naming these two cases 

1. `NotFoundError` Where there is no element matching the locator and filters.
2. `MatchError` The element _was_ found, but one or more of the filters in the `has()` or `is()` clause is missing.

let's take the following statement (adapted from actual FOLIO test case for a datepicker that stashes its value in a hidden, disabled text field):

```ts
await TextField("date", { visible: false, disabled: true}).has({ value: "2008-12-07T00:00:00.000+0000" });
```

Now, let's say that we _can_ find it. In other words, the locator and lookup attributes work. In this case, we would want an `InteractorMatchError`:

```
MatchError: text field 'date' with attributes { visible: false, disabled: false } does not match filter `value`:

expected ┃ value: "2008-12-07T00:00:00.000+0000" ┃
━━━━━━━━━┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋
  actual ┃            "2008-04-17T00:00:00.000Z" ┃
```

There are a couple of things to notice here:

- The "lookup" text is explicit and there is no attempt to translate it into English. I think it draws the eye more to the properties that the developer is looking for.
- This is more important. The original statement was formulated as an assertion: `has({ value: "2008-12-07T00:00:00.000+0000" });`. If something goes wrong there, we only show the differences in the expected values from the assertion, and the actual values. For cases, where the lookup filters do not match, that would be a `InteractorNotFoundError`

But what about the `NotFoundError`? Here is another statement found in FOLIO:

```js
await CalendarDays({ visible: false, disabled: true }).exists();
```

Here, is the case where we have lookup filters that fail to find the element. In this case, we would say:

```
NotFoundError: did not find 'calendar days' with attributes { visible: false, disabled: true }. But did find 2 others:

              ┃ visible: false ┃ disabled: true ┃
━━━━━━━━━━━━━━┣━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━┫
 1. Arrival   ┃              ✓ ┃          false ┃
 2. Departure ┃           true ┃          false ┃
```

1. We both clearly indicate what we were looking for that we did not find, and we show that we found 2 things that were close. 
2. We add the locator for each potential match for the row on the table
3. we don't copy the actual value if it matches the second. That's noise.

### Custom Matcher

Let's take a case where we want to make an assertion about the dimentions of the cell.

```ts
 await MultiColumnListCell({row: 0, column: 5 }).has({ width: greaterThan(0), height: 20 });
```

And let's say that the cell _can_ be found. In this case, our table will contain only the filters that are part of the assertion, but it will also contain the description of the match in the expected heading.

```
MatchError: multi-column list cell with { row: 0, column: 5} does not match filters `width`, and `height`

expected ┃ width: greater than 0 ┃ height: 20 ┃
━━━━━━━━━┣━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━┫
  actual ┃                     0 ┃      ✓     ┃
```

In order to implement this, we can define a matcher interface https://gist.github.com/cowboyd/0febbc2b94a31bb9bbaa308350c9a802


#### Summary

```
 FilterNotMatchingError: text field which is not visible and which is not disabled does not match filters:

        ┃ value: "2008-12-07T00:00:00.000+0000" ┃ visible: true ┃ disabled: false ┃
        ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━┫
        ┃ ⨯ "2008-04-17T00:00:00.000Z"          ┃ ⨯ false       ┃ ✓ false         ┃
```

becomes

```
MatchError: text field with attributes { visible: false, disabled: false } does not match filter `value`:

expected ┃ value: "2008-12-07T00:00:00.000+0000" ┃
━━━━━━━━━┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╋
  actual ┃            "2008-04-17T00:00:00.000Z" ┃
```
and

```
    NoSuchElementError: did not find calendar days which is not visible and which is disabled, did you mean one of:

        ┃ visible: false ┃ disabled: true ┃
        ┣━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━┫
        ┃ ✓ false        ┃ ⨯ false        ┃
        ┃ ⨯ true         ┃ ⨯ false        ┃
```

becomes

```
NotFoundError: did not find 'calendar days' with attributes { visible: false, disabled: true }. But did find 2 others:

              ┃ visible: false ┃ disabled: true ┃
━━━━━━━━━━━━━━┣━━━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━┫
 1. Arrival   ┃              ✓ ┃          false ┃
 2. Departure ┃           true ┃          false ┃
```

**Comment by jorgelainfiesta** [comment]
For me both errors are still confusing if you read them without the explanation. Thankfully my memory is terrible so I read your document, did other stuff for a few hours and came back to read the summary haha and here's what is unclear to me in the copy:

Both `MatchError` and `NotFoundError` suggest that they did find something but that one of their attributes didn't match exactly, why do I only get suggestions for the latter? Yet I get sort of a table for both. 

Now in this found options table we have to deal with double negatives which I guess it's a consequence of using what the person inputted. My suggestion would then be that we follow the check pattern too instead of using boolean values (also to be consistent).

**Comment by cowboyd** [comment]
> Both MatchError and NotFoundError suggest that they did find something

I don't doubt you, but do you not think that saying "NotFoundError: did not find...."  implies that something was found? Or are you saying that the distinction just isn't clear enough. How can we make it more clear in the cases where the interactor was found and the `is()/has()` clause does not match, vs the interactor was not found at all, and so the `is()/has()` clause was never even tried. How do you feel about the following?

```
NotFound: 'calendar days' with attributes { visible: false, disabled: true } does not exist. But did find 2 others:
```

```
MatchError: text field with attributes { visible: false, disabled: false } exists, but does not match filter `value`:
```

**Comment by jorgelainfiesta** [comment]
Perhaps I am just very confused about which syntax triggers which errors and the parallelism of the errors. I also don't understand when element is found or not based on filters, because `value` could also be an attribute?

**Comment by jnicklas** [comment]
Catching up on this discussion. I'm really liking @cowboyd's suggestions for improving the error messaging. Primarily, hiding the value in the case of a match is a really good idea, and separating into expected/actual will make it much clearer. I think the exact format we can tweak, but it's already looking much clearer.

As for the confusion between NotFoundError and MatchError, the necessity of differentiating between these stems from wanting to create as much clarity as possible, while still avoiding potential ambiguities.

An example:

``` typescript
TextField("Name", { value: "Jonas" }).exists();
TextField("Name").has({ value: "Jonas" });
```

These look like they do similar-ish things, but they are in fact *not* semantically equivalent, and I think this is where some of the confusion comes in. The first form essentially says:

> Is there a text field with label "Name" whose value is "Jonas"

And the second form says:

> Given that there is exactly one text field with label "Name", is its value "Jonas"?

In most cases, these are equivalent, but in some they are not. Imagine that there are *two* text fields with label "Name", one of which has the value "Jonas" and the other has the value  "Charles", should the assertion pass?

In this example, the first assertion will pass, and the second one will not.

> Is there a text field with label "Name" whose value is "Jonas"

Yes there is

> Given that there is exactly one text field with label "Name", is its value "Jonas"?

There are in fact *two* text fields with label "Name", so the condition has not been met and the assertion will fail.

**Comment by jbolda** [comment]
> As for the confusion between NotFoundError and MatchError, the necessity of differentiating between these stems from wanting to create as much clarity as possible, while still avoiding potential ambiguities.

The example that has come up a few times as I have been writing interactors is these two different assertions:
```javascript
TextField("Name").absent(); // asserts that it won't find this field in the DOM
TextField("Name").is({ visible: false }); // asserts that it exists in the DOM, but that you can't see it, i.e. display: none
```

That helped me mentally differentiate the two different errors.

**Comment by jorgelainfiesta** [comment]
Wow that makes it all so clear, thanks @jnicklas! Given that the errors respond directly to two different methods, can we make the error message respond to the intended meaning of the assertion? 

For example if we have this:
```js
TextField("Name", { value: "Jonas" }).exists(); // Is there a text field with label "Name" whose value is "Jonas"
```
Then the error could be:
```
*NotFound*: A `TextField` with label "Name" that matches the filter `{ value: "Jonas" }` does not exist.

  We found other `TextField`s, maybe one of them is what you were looking for?
  –––––––––––––––––––––––––––––––––––––
  |  TextField's label  |    Value    |
  –––––––––––––––––––––––––––––––––––––
  |  Name               |   "John"    |
  |  Email              |             |
```
And for the other one:
```js
TextField("Name").has({ value: "Jonas" }); // Given that there is exactly one text field with label "Name", is its value "Jonas"?
```
There's multiple possibilities for this one from what I understand so that means more errors?

One scenario where the matcher doesn't find the right element to check:
```
*MatchError*: Multiple TextField with label 'name' were found, but `has` can only match one element at a time.
  Consider adding filters to match one specific TextField.
```

Another one:
```
*MatchError*: `TextField` with label "Name" exists but it does not have`{ value: "Jonas" }` but `{ value: "John"}`.
```
