### ISSUE TITLE
Whenever i tried to create react app it shows module not find.

### ISSUE THREAD

**Issue by Ayushgh1017** [thefrontside/bigtest#912]
It is showing the error mentioned below
Error: Cannot find module './node.js'
Require stack:
- C:\Users\abhishek\AppData\Roaming\npm\node_modules\create-react-app\node_modules\debug\src\index.js
- C:\Users\abhishek\AppData\Roaming\npm\node_modules\create-react-app\node_modules\tar-pack\index.js
- C:\Users\abhishek\AppData\Roaming\npm\node_modules\create-react-app\createReactApp.js
- C:\Users\abhishek\AppData\Roaming\npm\node_modules\create-react-app\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\abhishek\AppData\Roaming\npm\node_modules\create-react-app\node_modules\debug\src\index.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\abhishek\\AppData\\Roaming\\npm\\node_modules\\create-react-app\\node_modules\\debug\\src\\index.js',
    'C:\\Users\\abhishek\\AppData\\Roaming\\npm\\node_modules\\create-react-app\\node_modules\\tar-pack\\index.js',
    'C:\\Users\\abhishek\\AppData\\Roaming\\npm\\node_modules\\create-react-app\\createReactApp.js',
    'C:\\Users\\abhishek\\AppData\\Roaming\\npm\\node_modules\\create-react-app\\index.js'
  ]
}

**Comment by Ayushgh1017** [comment]
Plz solve this problem for me . I am beginner in this .

**Comment by cowboyd** [comment]
Hi @Ayushgh1017,

It looks like this is an issue with the `create-react-app`, and so my recommendation would be to [file your report there](https://github.com/facebook/create-react-app/issues/new?assignees=&labels=issue%3A+bug+report%2C+needs+triage&template=bug_report.md)

Good luck!
