### ISSUE TITLE
CRASH: project_1.jsTSConfig is not a function

### ISSUE THREAD

**Issue by johanms** [thefrontside/bigtest#969]
# Error Report

I get this error when running `yarn bigtest server --launch=chrome` after upgrading from bigtest `0.13.3` to `0.14.1`:

`TypeError: project_1.jsTSConfig is not a function`

<details><summary>diagnostics</summary>

Argv
----
server,--launch=chrome

Stack
-----
TypeError: project_1.jsTSConfig is not a function
    at prepareInputOptions (/Users/johanms/workspace/fleks/fleks-marketing/node_modules/@bigtest/bundler/dist/bundler.js:54:89)
    at prepareWatchOptions (/Users/johanms/workspace/fleks/fleks-marketing/node_modules/@bigtest/bundler/dist/bundler.js:87:12)
    at Bundler.watch (/Users/johanms/workspace/fleks/fleks-marketing/node_modules/@bigtest/bundler/dist/bundler.js:114:37)
    at watch.next (<anonymous>)
    at /Users/johanms/workspace/fleks/fleks-marketing/node_modules/effection/dist/effection.js:1:7739
    at e.r.advance (/Users/johanms/workspace/fleks/fleks-marketing/node_modules/effection/dist/effection.js:1:7781)
    at e.r.enter (/Users/johanms/workspace/fleks/fleks-marketing/node_modules/effection/dist/effection.js:1:7701)
    at t.call (/Users/johanms/workspace/fleks/fleks-marketing/node_modules/effection/dist/effection.js:1:8325)
    at t.n.enter (/Users/johanms/workspace/fleks/fleks-marketing/node_modules/effection/dist/effection.js:1:4576)
    at t.call (/Users/johanms/workspace/fleks/fleks-marketing/node_modules/effection/dist/effection.js:1:9495)

</details>

**Comment by cowboyd** [comment]
Thanks @johanms for the bug report! I suspect that it might be related to a recently introduced change: #961
